# NumPy Operations

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic.

Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.

In [1]:
import numpy as np

a = np.arange(20)
a.ndim

1

In [2]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [3]:
print(a.reshape(4,5))
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [4]:
a.shape = 4,5
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [5]:
a.shape = 2,2,5
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [8]:
a = np.array( [20,30,40,50] )
b = np.arange( 1,2)

In [9]:
c = a-b
c

array([19, 29, 39, 49])

In [10]:
b**2

array([1], dtype=int32)

In [11]:
a

array([20, 30, 40, 50])

In [12]:
a < 35

array([ True,  True, False, False])

In [13]:
a[a<35]

array([20, 30])

Unlike in many matrix languages, the product operator * operates elementwise in 
NumPy arrays. 
The matrix product can be performed using the dot function or method:

In [14]:
a = np.arange(20)

In [15]:
a.shape = 2,10

In [16]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [17]:
b = a.reshape(5,4)

In [18]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [19]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [20]:
A = np.array( [[1,1],[0,1]] )
print(A.shape)
B = np.array( [[2,0],[3,4]] )
print(B.shape)

(2, 2)
(2, 2)


In [21]:
print(A)
print(B)
A*B

[[1 1]
 [0 1]]
[[2 0]
 [3 4]]


array([[2, 0],
       [0, 4]])

In [23]:
A.dot(B) #matrix product

array([[5, 4],
       [3, 4]])

In [24]:
B.dot(A)

array([[2, 2],
       [3, 7]])

In [25]:
np.dot(A, B)

array([[5, 4],
       [3, 4]])

Some operations, such as += and *=, act in place to modify an existing 
array rather than create a new one.

In [27]:
a = np.ones((2,3), dtype=np.int64)
b = np.random.random((2,3))

In [28]:
print(a)
print(b)

[[1 1 1]
 [1 1 1]]
[[0.44797969 0.02532382 0.18607206]
 [0.68677532 0.39210738 0.10084411]]


In [29]:
a *= 3 #equivalent to a=a*3
a

array([[3, 3, 3],
       [3, 3, 3]], dtype=int64)

In [30]:
b += a # equivalent to b=b+a
b

array([[3.44797969, 3.02532382, 3.18607206],
       [3.68677532, 3.39210738, 3.10084411]])

In [ ]:
float(4)

In [31]:
a += b  
# b is not automatically converted to integer type. cannot convert float to int

TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

# Universal Functions

In [32]:
B = np.arange(3)

In [33]:
B = np.arange(1,4) * 0

In [34]:
B

array([0, 0, 0])

In [35]:
np.any(B)

False

In [36]:
np.exp(B)

array([1., 1., 1.])

In [37]:
np.sqrt(B)

array([0., 0., 0.])

In [38]:
C = np.array([2, -1, 4.])

In [39]:
np.add(B, C)

array([ 2., -1.,  4.])

In [40]:
np.all([[True,True],[True,True]])

True

In [41]:
np.all([[True,False],[True,True]], axis=0)


array([ True, False])

In [ ]:
np.any([[0, 4, 8,7],[0,3,4,0]],axis=0)

In [42]:
np.all([1.0, np.nan])

#Not a Number (NaN), positive infinity and negative infinity evaluate to True 
#because these are not equal to zero.

True

In [44]:
data = range(1,5)

In [45]:
np.average(data)

2.5

In [46]:
np.average(range(1,11), weights=range(10,0,-1))

4.0

In [47]:
data = np.arange(6).reshape((3,2))
print(data)
np.average(data, axis=1, weights=[1./4, 3./4])
#Axis must be specified when shapes of a and weights differ.

[[0 1]
 [2 3]
 [4 5]]


array([0.75, 2.75, 4.75])

In [48]:
x = np.array([[5,6], [3,9],[0,8]])
print(x)
a = np.nonzero(x)
np.nonzero(x)

[[5 6]
 [3 9]
 [0 8]]


(array([0, 0, 1, 1, 2], dtype=int64), array([0, 1, 0, 1, 1], dtype=int64))

In [ ]:
len(a[0])

In [50]:
x[[0, 0, 1, 1, 2], [0, 1, 0, 1, 1]]

array([5, 6, 3, 9, 8])

In [49]:
x[np.nonzero(x)]

array([5, 6, 3, 9, 8])

In [52]:
np.transpose(x)

array([[5, 3, 0],
       [6, 9, 8]])

In [51]:
np.transpose(np.nonzero(x))

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1],
       [2, 1]], dtype=int64)

A common use for nonzero is to find the indices of an array, where a condition 
is True. Given an array a, the condition a > 3 is a boolean array and since 
False is interpreted as 0, np.nonzero(a > 3) yields the indices of the a 
where the condition is true

In [53]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [54]:
a > 3

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
a

In [ ]:
np.nonzero(a)

In [55]:
np.nonzero(a > 3)

(array([1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2], dtype=int64))

In [ ]:
(a > 3).nonzero()

In [ ]:
arr = np.arange(0,10)

In [ ]:
arr + arr

In [ ]:
arr * arr

In [ ]:
arr - arr

In [ ]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr/arr

In [ ]:
# Also warning, but not an error instead infinity
1/arr

In [ ]:
arr**3

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [ ]:
#Taking Square Roots
np.sqrt(arr)

In [ ]:
#Calcualting exponential (e^)
np.exp(arr)

In [ ]:
np.max(arr) #same as arr.max()

In [ ]:
np.sin(arr)

In [ ]:
np.log(arr)

In [56]:
a=float('nan')
type(a)

b=float('inf')

In [57]:
import math

In [58]:
math.isnan(a)

True

In [59]:
a=np.nan

In [60]:
np.nan

nan