NumPy package contains an iterator object numpy.nditer. It is an efficient multidimensional iterator object using which it is possible to iterate over an array. Each element of an array is visited using Python’s standard Iterator interface.

In [1]:
import numpy as np
a = np.arange(0,60,5)
a = a.reshape(3,4)

In [2]:
a

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

In [4]:
for x in np.nditer(a):
    print (x, end=" ")

0 5 10 15 20 25 30 35 40 45 50 55 

The order of iteration is chosen to match the memory layout of an array, without considering a particular ordering. This can be seen by iterating over the transpose of the above array.

In [5]:
a

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

In [6]:
b = a.T # transposing an array

In [7]:
b

array([[ 0, 20, 40],
       [ 5, 25, 45],
       [10, 30, 50],
       [15, 35, 55]])

In [8]:
for items in a:
    print(items, end = " ")

[ 0  5 10 15] [20 25 30 35] [40 45 50 55] 

In [10]:
for items in np.nditer(b):
    print(items, end = " ")

0 5 10 15 20 25 30 35 40 45 50 55 

In [10]:
for x in np.nditer(b): 
    print (x,end=" ")

0 5 10 15 20 25 30 35 40 45 50 55 

### Iteration order

In [11]:
a = np.arange(0,60,5)
a = a.reshape(3,4)
print(a)
b = a.T  #transposing
print(b)

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


In [12]:
c = b.copy(order='C')
print(c)

[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


In [13]:
for x in np.nditer(c):
    print (x,end=" ")

0 20 40 5 25 45 10 30 50 15 35 55 

In [14]:
c = b.copy(order='F')
print(c)
for x in np.nditer(c):
    print (x,end=" ")

[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0 5 10 15 20 25 30 35 40 45 50 55 

It is possible to force nditer object to use a specific order by explicitly mentioning it.

In [15]:
a = np.arange(0,60,5) 
a = a.reshape(3,4) 

In [16]:
a

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

In [17]:
a = np.arange(50).reshape(10,5)

In [18]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [19]:
# a[[7,4,9,0,2],[2,4,3,4,4]]

In [20]:
#fancy indexing
a[[1,2,0], # [1,2,0] -->specifying which rows to consider
#[1,2,3] ----> specifying which columns to take

SyntaxError: unexpected EOF while parsing (<ipython-input-20-5a172b4c351f>, line 3)

In [21]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [22]:
print(a)
for x in np.nditer(a, order = 'C'): 
    print (x,end=" ")  
print ('\n') 

print( 'Sorted in F-style order:' )
for x in np.nditer(a, order = 'F'): 
    print (x,end=" ") 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 

Sorted in F-style order:
0 5 10 15 20 25 30 35 40 45 1 6 11 16 21 26 31 36 41 46 2 7 12 17 22 27 32 37 42 47 3 8 13 18 23 28 33 38 43 48 4 9 14 19 24 29 34 39 44 49 

In [24]:
a=np.arange(20).reshape(4,5)
for x in np.nditer(a):
    print(x,end=' ')

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 

In [25]:
for x in np.nditer(a,order='F'):
    print(x,end=' ')

0 5 10 15 1 6 11 16 2 7 12 17 3 8 13 18 4 9 14 19 

In [ ]:
b=np.copy(a)

In [ ]:
b

In [ ]:
for x in np.nditer(b,order='F'):
    print(x,end=' ')

In [ ]:
c=np.copy(a,order='F')

In [ ]:
c

In [ ]:
for x in np.nditer(c):
    print(x, end=' ')