### NumPy Indexing and Selection

In [ ]:
import numpy as np

In [ ]:
li = [1,2,34,4]

In [ ]:
li[0]

In [ ]:
li[1:3]

In [ ]:
#Creating sample array
arr = np.arange(0,11)

In [ ]:
#Show
arr

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [ ]:
arr=arr*2
#Get a value at an index
arr

In [ ]:
arr[1]

In [ ]:
#Get values in a range
arr[1:5].reshape(2,2)

In [ ]:
#Get values in a range
arr[0:5]

In [ ]:
li = list(range(20))

In [ ]:
li

In [ ]:
li[1:8] = [100,100,100,100]

In [ ]:
li

In [ ]:
# new_li = li[:]  ====== li.copy()

In [ ]:
id(new_li) == id(li)

In [ ]:
arr

In [ ]:
arr[1:5] = 100
arr

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [ ]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

In [ ]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)
print(id(arr))
#Show
arr

In [ ]:
#Important notes on Slices
slice_of_arr = arr[0:6]
print(id(slice_of_arr))
#Show slice
slice_of_arr

In [ ]:
#Change Slice
slice_of_arr[:]=99
print(id(slice_of_arr))
#Show Slice again
slice_of_arr

In [ ]:
# s = "hello"
# print(s)
# a = "hi"
# a

In [ ]:
li = list(range(10))

In [ ]:
new_li = li[:]

In [ ]:
new = li

In [ ]:
id(li), id(new_li)

Now note the changes also occur in our original array!

In [ ]:
arr

Data is not copied, it's a view of the original array! This avoids memory problems!

In [ ]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

arr_copy[1:4]=2
print(arr_copy)

print(arr)

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [ ]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

In [ ]:
#Indexing row
arr_2d[1,2]


In [ ]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

In [ ]:
# Getting individual element value
print(arr_2d[1,0])
arr_2d

In [ ]:
arr_2d

In [ ]:
# 2D array slicing
# print(arr_2d)
#Shape (2,2) from top right corner
arr_2d[:2,1:]

In [ ]:
arr_2d[1,2]

In [ ]:
arr_2d[1:2,2:]

In [ ]:
#Shape bottom row
arr_2d[2:,:]

In [ ]:
#Shape bottom row
arr_2d[2,:] # : basically means i want all the rows or columns

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [ ]:
#Set up matrix
arr2d = np.zeros((10,10))
#print(arr2d)

In [ ]:
#Length of array
arr_length = arr2d.shape[1]
arr_length

In [ ]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

In [ ]:
a = np.random.rand(7,4)

In [ ]:
a

In [ ]:
arr = np.ones((8,4)) + np.random.random((8,4))

In [ ]:
arr

In [ ]:
# arr[[3,4,6,2]]

Fancy indexing allows the following

In [ ]:
arr[[2,3,1],[0]]

In [ ]:
arr[[[2,5,1,3],[0,2]]]

In [ ]:
arr[[2,1,5],[1,3,3]]

In [ ]:
#Allows in any order
arr2d[[6,4,2,7]]

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [2]:
import numpy as np

In [3]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [5]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [6]:
bool_arr = arr>4

In [7]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [8]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [9]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr = np.ones((3,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
arr=arr[0] * 2

In [13]:
arr

array([2., 2., 2., 2.])

In [14]:
arr=np.arange(25).reshape(5,5)

In [15]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [16]:
arr[[2,4,4],[1,3,4]]

array([11, 23, 24])

In [17]:
arr[[4,3,1]]

array([[20, 21, 22, 23, 24],
       [15, 16, 17, 18, 19],
       [ 5,  6,  7,  8,  9]])

In [20]:
arr[arr >= 5].reshape(4,5)

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr[:,4]

In [ ]:
a = np.arange(10).reshape(2,5)

In [ ]:
a

In [ ]:
a[0,2]

In [ ]:
a[:1,2:3]

In [21]:
arr = np.arange(20).reshape(4,5)

In [22]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [23]:
arr[1]

array([5, 6, 7, 8, 9])

In [24]:
arr[1,0]

5

In [25]:
arr[1][0]

5

In [26]:
arr[1:3]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [27]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [28]:
arr[1:3,3][1]

13

In [29]:
arr[1:3,0:2]

array([[ 5,  6],
       [10, 11]])

In [ ]:
arr

In [ ]:
arr[2:3,3]

In [ ]:
arr[2,3]

In [ ]:
arr

In [ ]:
arr[[3,2,1],[2,3,4]]

In [ ]:
arr

In [ ]:
arr = arr.flatten()

In [ ]:
arr

In [ ]:
arr[1:7] = 100

In [ ]:
arr

In [ ]:
arr

In [ ]:
for item in arr:
    print(item , end = " ")

In [ ]:
arr.shape = 4,5

In [ ]:
arr

In [ ]:
#nditer ===> n dimensional iterator

In [ ]:
for item in np.nditer(arr):
    print(item, end = " ")

In [ ]:
arr

In [ ]:
for item in np.nditer(arr, order = "F"):
    print(item, end = " ")

In [ ]:
for item in np.nditer(arr, order = "C"):
    print(item, end = " ")

In [ ]:
arr

In [ ]:
b = arr.copy(order = "F")

In [ ]:
arr

In [ ]:
b

In [ ]:
b.ndim

In [ ]:
for a in b:
    print(a, end = " ")
    print(type(a))