# Numpy Stats

# Order Stats

In [1]:
#amin ----- Return the minimum of an array or minimum along an axis.

Returns:	
amin : ndarray or scalar

Minimum of a. If axis is None, the result is a scalar value. If axis is given, the result is an array of dimension a.ndim - 1.

In [2]:
import numpy as np
a = np.arange(4).reshape((2,2))

In [3]:
a = a**2

In [4]:
a=a + 2

In [5]:
a

array([[ 2,  3],
       [ 6, 11]], dtype=int32)

In [6]:
np.amin(a)   #Minimum of the flattened array

2

In [7]:
np.argmin(a)

0

In [8]:
np.max(a)

11

In [9]:
np.amin(a, axis=1)   # Minima along the first axis

array([2, 6], dtype=int32)

In [10]:
a

array([[ 2,  3],
       [ 6, 11]], dtype=int32)

In [11]:
np.amin(a, axis=0)[0]   # Minima along the second axis

2

In [13]:
b = np.arange(5, dtype=float)

In [14]:
b[2] = np.NaN

In [15]:
b

array([ 0.,  1., nan,  3.,  4.])

In [16]:
np.amin(b)

D:\ana\lib\site-packages\numpy\core\fromnumeric.py:83: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)


nan

In [17]:
np.nanmin(b)

0.0

NaN values are propagated, that is if at least one item is NaN, the corresponding min value will be NaN as well. To ignore NaN values (MATLAB behavior), please use nanmin.

Don’t use amin for element-wise comparison of 2 arrays; when a.shape[0] is 2, minimum(a[0], a[1]) is faster than amin(a, axis=0)

In [20]:
a = np.array([[1, 2], [3, np.nan]])

In [21]:
np.nanmax(a) 
#Return the maximum of an array or maximum along an axis, ignoring any NaNs

3.0

In [22]:
np.nanmax(a, axis=0)

array([3., 2.])

In [23]:
np.max(a, axis=0)

D:\ana\lib\site-packages\numpy\core\fromnumeric.py:83: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)


array([ 3., nan])

In [21]:
np.nanmax(a, axis=1)

array([2., 3.])

In [22]:
np.nanmax([1, 2, np.nan])

2.0

In [23]:
np.nanmax([1, 2, np.nan, np.inf])

inf

In [24]:
np.isnan(np.nan)

True

In [25]:
np.isnan(np.inf)

False

In [26]:
np.isnan([np.log(-1.),1.,np.log(0)])

D:\ana\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.
D:\ana\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([ True, False, False])

In [27]:
np.log(0)

D:\ana\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


-inf

In [28]:
np.log(-1)

D:\ana\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


nan

#ptp -- peak to peak

#Range of values (maximum - minimum) along an axis.

In [29]:
x = np.arange(4).reshape((2,2))
x

array([[0, 1],
       [2, 3]])

In [30]:
np.ptp(x, axis=0)

array([2, 2])

In [31]:
np.ptp(x)

3

In [32]:
np.ptp(x,axis=1)

array([1, 1])

#percentile ------ http://www.dummies.com/education/math/statistics/how-to-calculate-percentiles-in-statistics/   check its working here

In [24]:
a = np.array([[10, 7, 4], [3, 2, 1]])

In [25]:
np.percentile(a, 50) 

3.5

In [26]:
np.median(a)

3.5

# Averages and variances

In [27]:
#median

In [28]:
a = np.array([[10, 7, 4], [3, 2, 1]])

np.median(a)

3.5

In [29]:
print(np.median(a, axis=0))

print(np.median(a, axis=1))



[6.5 4.5 2.5]
[7. 2.]


In [30]:
data = range(1,5)

In [31]:
np.average(data)

2.5

In [32]:
np.average(range(1,11), weights=range(10,0,-1))

4.0

In [33]:
data = np.arange(6).reshape((3,2))

In [34]:
data

array([[0, 1],
       [2, 3],
       [4, 5]])

In [35]:
np.average(data, axis=1, weights=[2,3])

array([0.6, 2.6, 4.6])

In [36]:
#mean

In [37]:
a = np.array([[1, 2], [3, 4]])

In [38]:
np.mean(a)

2.5

In [39]:
np.mean(a, axis=0)

array([2., 3.])

In [40]:
np.mean(a, axis=1)

array([1.5, 3.5])

In [41]:
#standard deviation

In [42]:
a = range(7)

In [43]:
np.var(a)

4.0

In [18]:
np.mod([1,2],[3,4])

array([1, 2], dtype=int32)

In [20]:
np.mod(1,3)

1

In [23]:
2%4

2

In [45]:
a = np.array([[1, 2], [3, 4]])

In [46]:
np.std(a)

1.118033988749895

In [47]:
np.std(a, axis=0)

array([1., 1.])

In [48]:
np.std(a, axis=1)

array([0.5, 0.5])

In [49]:
#variance

In [50]:
a = np.array([[1, 2], [3, 4]])

In [51]:
np.var(a)

1.25

In [52]:
np.var(a, axis=0)

array([1., 1.])

In [53]:
np.var(a, axis=1)

array([0.25, 0.25])

In [54]:
#nanmean

In [55]:
a = np.array([[1, np.nan], [3, 4]])

In [56]:
np.nanmean(a)

2.6666666666666665

In [57]:
np.nanmean(a, axis=0)
np.nanmean(a, axis=1)

array([1. , 3.5])

In [58]:
#similarly check for nanvar, nanstd

In [59]:
a = np.array([[1,2,3], [4,5,6]])

In [60]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
np.cumsum(a)

array([ 1,  3,  6, 10, 15, 21], dtype=int32)

In [62]:
np.cumsum(a, dtype=float)

array([ 1.,  3.,  6., 10., 15., 21.])

In [63]:
np.cumsum(a,axis=0)

array([[1, 2, 3],
       [5, 7, 9]], dtype=int32)