In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])

In [3]:
arr

array([1, 2, 3, 4])

In [5]:
arr.shape

(4,)

In [6]:
arr.ndim

1

In [7]:
arr.shape = 4,1

In [8]:
arr

array([[1],
       [2],
       [3],
       [4]])

In [9]:
np.array([[1],[2],[3],[4]])

array([[1],
       [2],
       [3],
       [4]])

In [10]:
np.array([1,2,3])

array([1, 2, 3])

In [12]:
a = np.array([[1,2,3],[4,5,6]])

In [13]:
a.shape

(2, 3)

In [14]:
a.size

6

In [15]:
a.shape[0]

2

In [16]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [18]:
arr = np.arange(16).reshape((4,4))

In [19]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [20]:
arr.shape

(4, 4)

In [21]:
arr.ndim

2

In [22]:
arr.shape = 2,4,2

In [23]:
arr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

In [28]:
np.linspace(2,10, 50).reshape(25,2)

array([[ 2.        ,  2.16326531],
       [ 2.32653061,  2.48979592],
       [ 2.65306122,  2.81632653],
       [ 2.97959184,  3.14285714],
       [ 3.30612245,  3.46938776],
       [ 3.63265306,  3.79591837],
       [ 3.95918367,  4.12244898],
       [ 4.28571429,  4.44897959],
       [ 4.6122449 ,  4.7755102 ],
       [ 4.93877551,  5.10204082],
       [ 5.26530612,  5.42857143],
       [ 5.59183673,  5.75510204],
       [ 5.91836735,  6.08163265],
       [ 6.24489796,  6.40816327],
       [ 6.57142857,  6.73469388],
       [ 6.89795918,  7.06122449],
       [ 7.2244898 ,  7.3877551 ],
       [ 7.55102041,  7.71428571],
       [ 7.87755102,  8.04081633],
       [ 8.20408163,  8.36734694],
       [ 8.53061224,  8.69387755],
       [ 8.85714286,  9.02040816],
       [ 9.18367347,  9.34693878],
       [ 9.51020408,  9.67346939],
       [ 9.83673469, 10.        ]])

In [29]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
arr.dtype

dtype('int32')

In [33]:
np.array((1,2,3), dtype= np.int32)

array([1, 2, 3])

In [34]:
arr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

In [35]:
arr.shape = 4,4

In [36]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [37]:
arr *4

array([[ 0,  4,  8, 12],
       [16, 20, 24, 28],
       [32, 36, 40, 44],
       [48, 52, 56, 60]])

In [39]:
# [1,2,3] * 2

In [42]:
arr =  arr + 3

In [44]:
[1,2,3] + [3]

[1, 2, 3, 3]

In [45]:
arr

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14],
       [15, 16, 17, 18]])

In [46]:
arr[0]

array([3, 4, 5, 6])

In [47]:
arr[0,0]

3

In [48]:
arr[2,3]

14

In [49]:
arr

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14],
       [15, 16, 17, 18]])

In [50]:
arr[2][3]

14

In [51]:
# arr[row, columns]
# arr[row][column]

In [52]:
arr[-1]

array([15, 16, 17, 18])

In [53]:
arr

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14],
       [15, 16, 17, 18]])

In [54]:
arr[:, 3]

array([ 6, 10, 14, 18])

In [55]:
arr[:,3:]

array([[ 6],
       [10],
       [14],
       [18]])

In [56]:
arr[0:2,:3]

array([[3, 4, 5],
       [7, 8, 9]])

In [57]:
arr

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14],
       [15, 16, 17, 18]])

In [59]:
arr[[0,3,2]]  #fancy indexing

array([[ 3,  4,  5,  6],
       [15, 16, 17, 18],
       [11, 12, 13, 14]])

In [60]:
arr[[0,3,2], [2]]

array([ 5, 17, 13])

In [62]:
arr[[0,3,2], [2,2,2]]

array([ 5, 17, 13])

In [63]:
arr

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14],
       [15, 16, 17, 18]])

In [64]:
np.mean(arr)

10.5

In [65]:
np.mean(arr, axis=0)

array([ 9., 10., 11., 12.])

In [67]:
# sum([3,7,11,15])/4

In [68]:
np.mean(arr, axis = 1)

array([ 4.5,  8.5, 12.5, 16.5])

In [69]:
np.var(arr)

21.25

In [70]:
np.std(arr)

4.6097722286464435

In [72]:
np.min(arr, axis = 0)

array([3, 4, 5, 6])

In [73]:
np.cumsum(arr)

array([  3,   7,  12,  18,  25,  33,  42,  52,  63,  75,  88, 102, 117,
       133, 150, 168], dtype=int32)

In [74]:
np.cumsum(arr, axis=1)

array([[ 3,  7, 12, 18],
       [ 7, 15, 24, 34],
       [11, 23, 36, 50],
       [15, 31, 48, 66]], dtype=int32)

In [75]:
arr

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14],
       [15, 16, 17, 18]])

In [76]:
np.ptp(arr)

15

In [77]:
np.median(arr)

10.5

In [84]:
np.percentile(range(1,11),90, interpolation="nearest")

9

In [85]:
np.percentile(arr, 90)

16.5

In [86]:
arr

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14],
       [15, 16, 17, 18]])

In [87]:
arr = arr.ravel()

In [88]:
arr

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18])

In [89]:
np.any(arr)

True

In [90]:
arr[3] = 0

In [91]:
arr

array([ 3,  4,  5,  0,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18])

In [92]:
np.any(arr)

True

In [93]:
np.all(arr)

False